import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sheared/Navbar";
import Footer from "@/components/sheared/Footer";

const outFit = Outfit({
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outFit.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <Navbar/>
        <main className="flex-1">

        {children}
        </main>
        <Footer />
        </body>
    </html>
  );
}
